version: '3.8'

services:
  # Вычислительное ядро и сервер дистрибуции данных (FastAPI Backend)
  ssm_backend:
    build: .
    container_name: ssm_backend_container
    ports:
      - "8000:8000"
    volumes:
      - ssm_shared_data:/app/shared_data
      - .:/app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1

  # Панель триажа рисков верхнего уровня (Streamlit Frontend)
  ssm_dashboard:
    build: .
    container_name: ssm_dashboard_container
    command: streamlit run interface/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ssm_shared_data:/app/shared_data
      - .:/app
    depends_on:
      - ssm_backend
    restart: always

volumes:
  ssm_shared_data:
